name: Integration

on:
  push:
    branches:
      - test/ci

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q -r ./cicd_pipeline/ci_pipeline/requirements.txt
          pip install -q black isort mypy pytest pytest-cov

      - name: Change directory
        run: cd cicd_pipeline/ci_pipeline

      - name: Formatting with black
        run: |
          black --check ./cicd_pipeline/ci_pipeline/

      - name: Run isort for import sorting
        run: isort --check-only ./cicd_pipeline/ci_pipeline/

      - name: Type Checking with Mypy
        run: mypy ./cicd_pipeline/ci_pipeline/

      - name: Run tests with Pytest
        run: pytest ./cicd_pipeline/ci_pipeline/

      - name: Check code coverage with pytest-cov
        run: pytest --cov=./cicd_pipeline/ci_pipeline/ --cov-report=term-missing --cov-fail-under=70 ./cicd_pipeline/ci_pipeline/tests