name: Integration

on:
  push:
    branches:
      - test/ci
#   pull_request:
#     branches:
#       - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q -r ./cicd_pipeline/ci_pipeline/requirements.txt
          pip install -q black isort mypy pytest pytest-cov

      - name: Run Super-Linter with Black
        uses: super-linter/super-linter@v6.4.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_BLACK: true
          PYTHON_BLACK_CONFIG: "--check --diff"

      - name: Run isort for import sorting
        run: isort --check-only ./cicd_pipeline/ci_pipeline

      - name: Type Checking with Mypy
        run: mypy ./cicd_pipeline/ci_pipeline